### ISSUE TITLE
permit global or shared variables

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/vizlab#103]
It would be great to have global variables. For example, states, start.date, and end.date was required to be defined in at least 3 different places in the yaml for the hurricane viz.

**Comment by eread-usgs** [comment]
Possibly complete or partially complete. But need an example and some requirements for what is actually needed.

**Comment by ldecicco-USGS** [comment]
```
fetch:
  -
    id: viz_config
    states: ["WI","MI"]
    reader: rds
```
Maybe just that?

Also, look at markdown reader
