### ISSUE TITLE
thumbnail section of viz.yaml not initialized correctly

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/vizlab#165]
The thumbnail section comes back as:

```
thumbnail:    url:    width: 250    height: 250    alttext:fetch:
```

instead of:

```
thumbnail:    
    url:    
    width: 250    
    height: 250    
    alttext:
    fetch:
```

See https://github.com/USGS-VIZLAB/vizlab/blob/master/R/vizSkeleton.R
