### ISSUE TITLE
Refetch work

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/vizlab#192]
Check the test, make sure it's working.

**Comment by aappling-usgs** [comment]
this could be a bandaid on the way to fully implementing #102, or a complement to that future work.

specific example: we want a block like this to not run each time:
```  -
    id: precip-data
    fetcher: precip
    start.date: "2017-09-07"
    end.date: "2017-09-08"
    scripts: scripts/fetch/fetchPrecip.R
    location: cache/precip.csv
    mimetype: text/csv
    refetch: FALSE
    depends:
      counties: counties
    comment: disabling refetch to avoid too many GDP requests
```
and yet it seems to be running each time

**Comment by aappling-usgs** [comment]
at first, refetch=TRUE was supposed to mean don't ever cache this
then later we thought refetch=FALSE was supposed to mean don't ever refetch this
clearly communication will need to be part of this solution

**Comment by aappling-usgs** [comment]
here's what refetch claims to do right now (https://github.com/USGS-VIZLAB/vizlab/blob/0.2.x/vignettes/vizlabExample.Rmd#controlling-the-fetch-section):
> By default, the refetch option is set to TRUE in the viz.yaml for each section. vizlab checks the timestamps of online resources to see if the file or resource has changed since it was last fetched. If the timestamp has changed, or a timestamp cannot be obtained, the data will be fetched again. However, this may be undesireable in some scenarios. To force vizlab to use the cached versions of remote files, set refetch to FALSE in the relevant sections of the viz.yaml. Conversely, to force vizlab to refetch the data regardless of timestamps, set refetch to TRUE and delete the timestamps for each section. These are stored in vizlab/make/timestamps.

**Comment by aappling-usgs** [comment]
experience in irma (quotes & summaries from slack)

1. how does one get a block like this to not run each time (because it still is):
```
  -
    id: precip-data
    fetcher: precip
    start.date: "2017-09-07"
    end.date: "2017-09-08"
    scripts: scripts/fetch/fetchPrecip.R
    location: cache/precip.csv
    mimetype: text/csv
    refetch: FALSE
    depends:
      counties: counties
    comment: disabling refetch to avoid too many GDP requests
```

2. "it was always a bit goofy I think", "I don't think it has ever worked as expected"

3. people forget that refetch=TRUE (e.g., they had it at FALSE but then pull as TRUE, don't notice) and then get frustrated that it's refetching

4. the way that folks are coding re-fetch in functions doesn't work well, since it doesn't end up fetching the first time.
e.g.
```
if(viz[["refetch"]]){
   do stuff
} else {
   return(NULL)
}
```

5. if you have it set to false and you code in the check like that, the target doesn't built when you change the code
