### ISSUE TITLE
ability to depend on a file

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/vizlab#195]
I think this kind of thing should be really easy, but the simple way doesn't work
```yaml
    depends: 
      view-limits: view-limits
      storm-states: storm-states
      storm-counties: storm-counties
      storm-islands: storm-islands
      storm-track: storm-track
      storm-sites: storm-sites
      css: layout/css/hurricane-svg.css
```
readDepends(viz)
Error in match(no.match, c(`NA` = NA, stop = stop("Could not find ", x))) : 
  Could not find layout/css/hurricane-svg.css
