### ISSUE TITLE
trouble with remake sources

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#292]
For issue #246 and PR #281 , the scripts I list as remake `sources` don't seem to be getting sourced. I'll keep working on it but would also welcome help - can y'all reproduce and/or diagnose this issue, @jread-usgs and others? 

Here's a simple remake.yml that I just created in my copy of USGS-VIZLAB/example:
```yml
packages:
  - vizlab
sources:
  - scripts/fetch/cars.R
targets:
  all:
    depends:
      - 'cache/cars.csv'
  'cache/cars.csv':
    command: fetch(I('cars-data'))
```
when I run `remake::make()` in a fresh R session (after deleting the .remake folder if it exists), I get this:
```r
> remake::make()
[  LOAD ] 
[  READ ]                |  # loading sources
<  MAKE > all
[ BUILD ] cache/cars.csv |  fetch("cars-data")
[  READ ]                |  # loading packages
Restoring previous version of cache/cars.csv
Error in UseMethod("fetch") : 
  no applicable method for 'fetch' applied to an object of class "c('cars', 'fetcher', 'fetch', 'viz')"
```
but if I then source the script manually and try again, everything works much better:
```r
> source('scripts/fetch/cars.R')
> remake::make()
<  MAKE > all
[ BUILD ] cache/cars.csv |  fetch("cars-data")
[ ----- ] all
```

This same pattern holds even if I copy scripts/fetch/cars.R into the top-level directory and change `sources` to simply `cars.R`, and even if I declare it in one line: `sources: cars.R`.

I'm up to date on `remake`:
```r
> packageVersion('remake')
[1] ‘0.3.0’
> devtools::install_github('richfitz/remake')
Using GitHub PAT from envvar GITHUB_PAT
Skipping install of 'remake' from a github remote, the SHA1 (e29028b5) has not changed since last install.
  Use `force = TRUE` to force installation
```

Any ideas why this is happening or how to make my `sources:` get `source()`d?

**Comment by aappling-usgs** [comment]
Narrowed it down a bit - I think the problem is that `remake` is so selective about what it loads that it's not bothering to load `fetch.cars` when the command just says `fetch()`.

In a new, nearly empty directory, I have these three files:

### cars.R
```r
fetch.cars <- function(viz) {
  viz <- as.viz(viz)
  id <- viz[['id']]
  location <- viz[['location']]
  write.csv(x=cars, file=location, row.names=FALSE)
}

fetchTimestamp.cars <- vizlab:::fetchTimestamp.file
```

### viz.yaml
```yml
fetch:
  -
    id: cars-data
    location: cars.csv
    fetcher: cars
    mimetype: text/csv
    scripts: scripts/fetch/cars.R
```

### remake.yml
```yml
packages:
  - vizlab
sources: 
  - cars.R
targets:
  all:
    command: fetch(I('cars-data'))
```

In a fresh R session, this reproduces the error:
```r
> remake::make()
[  LOAD ] 
[  READ ]       |  # loading sources
<  MAKE > all
[ BUILD ] all   |  all <- fetch("cars-data")
[  READ ]       |  # loading packages
Error in UseMethod("fetch") : 
  no applicable method for 'fetch' applied to an object of class "c('cars', 'fetcher', 'fetch', 'viz')"
```

but if I change the `command` in remake.yml to this:
```yml
    command: fetch.cars(I('cars-data'))
```

then the build works:
```
> remake::make()
[  LOAD ] 
[  READ ]       |  # loading sources
<  MAKE > all
[ BUILD ] all   |  all <- fetch.cars("cars-data")
[  READ ]       |  # loading packages
```
