### ISSUE TITLE
add viz ids as targets for all recipes

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#312]
For remake. Currently (in the remake feature branch), viz items that represent files have the file destination location as the target of their remake recipe. This is appropriate, but it'd also be nice to have an object target that has the same name as the viz ID. Then we could call

```r
vizmake('iris-data')
```
whereas currently we'd need to call
```r
vizmake('data/iris.csv')
```
which requires looking up the item destination.

Such object targets can be defined with remake blocks like these:
```yml
  iris-data:
    command: readData('iris-data')
    depends:
      - data/iris.csv
      - scripts/read/myCsvReader.R
  data/iris.csv:
    command: fetch(I('iris-data'))

  cars-data:
    command: readData('cars-data')
    depends:
      - cache/cars.csv
      - scripts/read/myCsvReader.R
  cache/cars.csv:
    command: fetch(I('cars-data'))
    depends:
      - vizlab/remake/scripts/cars-data.R
```

where in the above example I've further suggested that the value of the symbolic target output could be the outcome of `readData('vizid')`, saving an additional step at the command line. This bonus feature requires a bit of thought because not all target types have readers (e.g., publish sections don't). A further opportunity arising from this approach is that downstream targets could have the ids as dependencies, which would bring any changes in `readData` methods into the scope of the remake dependency management system. (Currently if you edited a readData method you'd need to explicity tell `make` or `remake` to rebuild the files that rely on that method to read other viz items.)
