### ISSUE TITLE
social-media-template is missing something?

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/vizlab#325]
When I run `vizmake()` with the [d3 branch of vizstorm](https://github.com/USGS-VIZLAB/vizstorm/tree/d3) , I get a warning about the social media template being unavailable:

```
In FUN(X[[i]], ...) :
  cannot find dependency '' of viz item 'social-media-template' so cannot include the dependency in remake.yaml
```

Briefly looking at the [line where the warning is thrown](https://github.com/USGS-VIZLAB/vizlab/blob/9666a3e101f10be7fc56b996a17b9e3e1455f6f7/R/createRemakefile.R#L26), makes me think that it is because I am not including a social media template in my publish step. If so, that warning might be annoyhing. There will probably be times where we don't want to use social media icons.

**Comment by ldecicco-USGS** [comment]
I tried to make a fully-functional application here:

https://github.com/USGS-VIZLAB/example

In your viz.yaml, co you have something like:
```
publish: 
   depends:       
      social: social-section
      vertical-social: vertical-social-section
      socialCSS: lib-social-media-css
...
context:
      title: Testing
      sections: [ "social", ]
      resources: [ "socialCSS"]

  -
    id: social-section
    template: social-media-template
    publisher: social
    depends: social-links
    context:
      embedLink: embed-dots.html
      facebookLink: http://www.facebook.com/sharer.php?u=https%3A%2F%2Fowi.usgs.gov%2Fvizlab%2FEXAMPLE%2F
      
```
At some point I had worked out using and not using the social icons... let me know if this doesn't help and I'll go poking around
